import nodemailer from "nodemailer";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { summary, clientInfo, practiceArea } = await req.json();

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER!,
        pass: process.env.GMAIL_APP_PASSWORD!,
      },
    });

    // Convert clean plain text summary to styled HTML
    const lines = summary.split("\n");
    let htmlBody = "";

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        htmlBody += "<br>";
        continue;
      }

      // Main title (has === underline or is all caps with more than 3 words)
      if (trimmed === "=====================" || trimmed === "---") {
        continue; // Skip decorative lines
      }

      // Section headers: ALL CAPS lines (at least 2 words, all uppercase)
      if (
        trimmed === trimmed.toUpperCase() &&
        trimmed.length > 3 &&
        /[A-Z]/.test(trimmed) &&
        !/^\d/.test(trimmed)
      ) {
        if (trimmed.includes("CLIENT INTAKE SUMMARY")) {
          htmlBody += `<h1 style="color:#1e3a5f; font-size:22px; border-bottom:3px solid #2563eb; padding-bottom:10px; margin:20px 0 10px;">${trimmed}</h1>`;
        } else {
          htmlBody += `<h2 style="color:#2563eb; font-size:16px; margin:20px 0 8px; border-bottom:1px solid #e2e8f0; padding-bottom:6px;">${trimmed}</h2>`;
        }
        continue;
      }

      // Numbered items
      if (/^\d+\.\s/.test(trimmed)) {
        htmlBody += `<p style="margin:4px 0 4px 16px; color:#334155; font-size:14px;">&#8226; ${trimmed.replace(/^\d+\.\s*/, "")}</p>`;
        continue;
      }

      // Key-value pairs (Name: John)
      if (/^[A-Z][a-zA-Z\s]+:/.test(trimmed)) {
        const [key, ...rest] = trimmed.split(":");
        const value = rest.join(":").trim();
        htmlBody += `<p style="margin:3px 0; font-size:14px; color:#334155;"><strong style="color:#1e3a5f;">${key}:</strong> ${value}</p>`;
        continue;
      }

      // Regular text
      htmlBody += `<p style="margin:4px 0; font-size:14px; color:#334155; line-height:1.6;">${trimmed}</p>`;
    }

    const mailOptions = {
      from: `"Legal Intake AI" <${process.env.GMAIL_USER}>`,
      to: process.env.LAWYER_EMAIL!,
      subject: `New Intake: ${clientInfo.name} - ${practiceArea}`,
      html: `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 700px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%); color: white; padding: 28px; border-radius: 12px 12px 0 0;">
            <h1 style="margin:0; font-size:24px; font-weight:700;">New Client Intake Report</h1>
            <p style="margin:8px 0 0; opacity:0.85; font-size:14px;">Generated by Legal Intake AI Widget</p>
          </div>
          <div style="background: #ffffff; padding: 28px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;">
            ${htmlBody}
          </div>
          <p style="text-align:center; color:#94a3b8; font-size:11px; margin-top:16px;">
            This report was automatically generated by AI. Please review all details before proceeding.
          </p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Email send error:", error);
    return NextResponse.json(
      { error: "Failed to send email.", details: String(error) },
      { status: 500 }
    );
  }
}
